export const motivations = [
    "You've got this — one focused hour changes everything.",
    "Small wins today = massive confidence tomorrow.",
    "Progress, not perfection. Keep going 💙",
    "Your potential is endless. Go do what you were created to do.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The future depends on what you do today.",
    "It always seems impossible until it's done.",
    "Start where you are. Use what you have. Do what you can.",
    "Dream big and dare to fail.",
    "You count! You matter! The world needs you!",
    "Focus on being productive instead of busy.",
    "Every moment is a fresh beginning.",
    "Don't wait. The time will never be just right.",
    "Action is the foundational key to all success.",
    "Your best teacher is your last mistake.",
    "Go for it. Whether it ends good or bad, it was an experience.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Believe in yourself and all that you are.",
    "There is no substitute for hard work.",
    "What defines us is how well we rise after falling.",
    "Make each day your masterpiece.",
    "Limit your 'always' and your 'nevers'.",
    "Nothing is impossible. The word itself says 'I'm possible!'",
    "You are capable of amazing things.",
    "Stay positive, work hard, make it happen.",
    "Don't stop when you're tired. Stop when you're done.",
    "Do something today that your future self will thank you for.",
    "Little by little, one travels far.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t let yesterday take up too much of today.",
    "You are stronger than you think.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop until you’re proud.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
];

export const getRandomMotivation = () => {
    const randomIndex = Math.floor(Math.random() * motivations.length);
    return motivations[randomIndex];
};
